version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
#            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
#            chmod +x /bin/hadolint
            
      - save_cache:
          paths: ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}


      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD

      - docker/build:
          image: mohawkadmin/capstone
          tag: "2.0"
      - docker/push:
          image: mohawkadmin/capstone
          tag: "2.0"


# jobs:
#   build:
#     docker:
#     # Use the same Docker base as the project
#       - image: python:3.7.3-stretch

#     working_directory: ~/repo

    # steps:
    #   - checkout
    #   # Download and cache dependencies
    #   - restore_cache:
    #       keys:
    #         - v1-dependencies-{{ checksum "requirements.txt" }}
    #         # fallback to using the latest cache if no exact match is found
    #         - v1-dependencies-

#       - run:
#           name: install dependencies
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             make install
#             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
#             chmod +x /bin/hadolint
            
#       - save_cache:
#           paths: ./venv
#           key: v1-dependencies-{{ checksum "requirements.txt" }}

#       # run lint!
#       - run:
#           name: run lint
#           command: |
#             . venv/bin/activate
#             make lint 

#       #push to DockerHub
#       - run:
#           name: push to Docker
#           command: |
#             sh run_docker.sh


workflows:
  default:
    jobs:
      - build-and-push